# Generated by Django 4.2.7 on 2024-04-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
