# Generated by Django 4.2.7 on 2024-04-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseApp', '0002_alter_sensorimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorimage',
            name='name',
            field=models.CharField(default='Sensor', max_length=16),
        ),
    ]
